# permissions for end users to edit imagebuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: imagebuild-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-container-image
    app.kubernetes.io/part-of: kube-container-image
    app.kubernetes.io/managed-by: kustomize
  name: imagebuild-editor-role
rules:
- apiGroups:
  - image.driedmango.org
  resources:
  - imagebuilds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - image.driedmango.org
  resources:
  - imagebuilds/status
  verbs:
  - get
