apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: image-builder
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ""
    resources:
      - secrets

  - verbs:
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - ""
    resources:
      - pods/finalizers
      - pods

  - apiGroups:
      - image.driedmango.io
    resources:
      - imagebuilds
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - image.driedmango.io
    resources:
      - imagebuilds/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: image-builder-binding
subjects:
  - kind: ServiceAccount
    name: image-builder-sa
    namespace: bc-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: image-builder
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-builder-sa
  namespace: bc-system


