apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-build
  namespace: bc-system
  labels:
    app: image-builder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-builder
      app.kubernetes.io/name: image-builder
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: image-builder
        app.kubernetes.io/name: image-builder
    spec:
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: ''            
      containers:
        - name: image-builder
          image: registry.us-west-1.aliyuncs.com/dried-mango/image-build:v0.4
          command:
            - /manager
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources: {}
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: image-builder-sa
      serviceAccount: image-builder-sa
      securityContext: {}
      schedulerName: default-scheduler
  progressDeadlineSeconds: 600
