apiVersion: v1
kind: Pod
metadata:
  name: image-build-test-pod
  namespace: default
spec:
  containers:
    - name: nginx
      image: registry.us-west-1.aliyuncs.com/dried-mango/nginx:1.27.0
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
      resources: {}
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  securityContext: {}

