/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	imagedriedmangoiov1 "github.com/driedmango520/kube-container-image/api/image.driedmango.io/v1"
	versioned "github.com/driedmango520/kube-container-image/pkg/client/clientset/versioned"
	internalinterfaces "github.com/driedmango520/kube-container-image/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/driedmango520/kube-container-image/pkg/client/listers/image.driedmango.io/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ImageBuildInformer provides access to a shared informer and lister for
// ImageBuilds.
type ImageBuildInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ImageBuildLister
}

type imageBuildInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewImageBuildInformer constructs a new informer for ImageBuild type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewImageBuildInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredImageBuildInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredImageBuildInformer constructs a new informer for ImageBuild type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredImageBuildInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ImageV1().ImageBuilds(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ImageV1().ImageBuilds(namespace).Watch(context.TODO(), options)
			},
		},
		&imagedriedmangoiov1.ImageBuild{},
		resyncPeriod,
		indexers,
	)
}

func (f *imageBuildInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredImageBuildInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *imageBuildInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&imagedriedmangoiov1.ImageBuild{}, f.defaultInformer)
}

func (f *imageBuildInformer) Lister() v1.ImageBuildLister {
	return v1.NewImageBuildLister(f.Informer().GetIndexer())
}
